### PR TITLE
Added indian passwords wordlist

### PR DESCRIPTION
**Pull request by PiyushDive**
I have added commonly used indian passwords wordlist which will help people not to set these passwords as their passwords. Also it will help in password cracking.

### CODE REVIEW

**Review by vaibhav3022 — APPROVED** [review]
This is valid contribution. All the changes are correct

**Comment by kkrypt0nn** [comment]
> This is valid contribution. All the changes are correct 

No. The wordlist is not [sorted](https://appdevtools.com/sort-lines) as the contribution guidelines mention.

**Review by kkrypt0nn — CHANGES_REQUESTED** [review]
See comment above

**Comment by kkrypt0nn** [comment]
Any updates @PiyushDive?

**Pull request closed without merging**
