### PR TITLE
added new section of top Indian female names

### PR DESCRIPTION
**Pull request by Abhishek19-dev**
I found that there were  no section top Indian female names . So i added some popular Indian female names . Hope you like it

### CODE REVIEW

**Review by kkrypt0nn — CHANGES_REQUESTED** [review]
Could you please sort them alphabetically 🫡

**Comment by Abhishek19-dev** [comment]
> Could you please sort them alphabetically 🫡

yes sure , I will do it

**Comment by Abhishek19-dev** [comment]
@kkrypt0nn Done , please review it.

**Review by kkrypt0nn — APPROVED** [review]
Thanks

**Pull request merged**
