### PR TITLE
some new user agent strings for BeOS

### PR DESCRIPTION
**Pull request by Priyanshuthapliyal2005**
add some new user agent strings for BeOS

### CODE REVIEW

**Comment by kkrypt0nn** [comment]
Hey there - thanks for the contribution, could you please provide your source as well? Thanks in advance

**Review by kkrypt0nn — APPROVED** [review]

**Comment by Priyanshuthapliyal2005** [comment]
Subject: Clarification Regarding Labeled Pull Request as "Invalid Spam"

Hello @kkrypt0nn ,

I hope this message finds you well. I am writing to seek clarification regarding the recent pull request (#50) titled "Some New User Agent Strings for BeOS" that I submitted to the "kkrypt0nn/wordlists" repository.

I noticed that the pull request was initially labeled as "invalid spam" and subsequently merged after providing the requested source information. I appreciate your prompt attention to the contribution and the merging of the pull request.

In an effort to improve and ensure adherence to the repository guidelines, I would like to understand the specific reasons for the initial "invalid spam" label. I provided the following sources for the added user agent strings:

1. https://user-agents.net/browsers/seamonkey
2. https://github.com/danielmiessler/SecLists

I want to ensure that my future contributions align with the repository's standards, and any feedback on the labeled status would be immensely helpful.

Thank you for your time and consideration. I look forward to your response and appreciate your efforts in maintaining the "kkrypt0nn/wordlists" repository.

Best regards,

Priyanshu Thapliyal
GitHub Username: Priyanshuthapliyal2005

**Comment by kkrypt0nn** [comment]
See #22

**Comment by Priyanshuthapliyal2005** [comment]
Ok cool , I appreciate it.

**Pull request merged**
