### PR TITLE
Created top male names in Canada 

### PR DESCRIPTION
**Pull request by Alisha-786**
I have added a text file of top male names in Canada. Kindly check and merge my pull request.

### CODE REVIEW

**Review by kkrypt0nn — CHANGES_REQUESTED** [review]
Please [order them alphabetically](https://appdevtools.com/sort-lines). Next time do the PRs as one as well, thanks.

**Comment by Alisha-786** [comment]
I have updated and ordered all the names in alphabetical order. Kindly, please check once again

**Review by kkrypt0nn — APPROVED** [review]
Thanks! 👍

**Comment by Alisha-786** [comment]
Can you label this as hactoberfest-accepted?

**Pull request merged**
