### PR TITLE
adding some names in top india males list 

### PR DESCRIPTION
**Pull request by Abhishek19-dev**
I found this project very useful and i have added some more indian males name . Hope you will consider it

### CODE REVIEW

**Review by kkrypt0nn — APPROVED** [review]

**Comment by Abhishek19-dev** [comment]
@kkrypt0nn may i know why did you label this PR as spam.

**Comment by kkrypt0nn** [comment]
Feel free to take a read at the following:

* #22

**Comment by Abhishek19-dev** [comment]
> Feel free to take a read at the following:
> 
> * [About Hacktoberfest #22](https://github.com/kkrypt0nn/wordlists/issues/22)

Ok cool , I appreciate it.

**Comment by Abhishek19-dev** [comment]
> > Feel free to take a read at the following:
> > 
> > * [About Hacktoberfest #22](https://github.com/kkrypt0nn/wordlists/issues/22)
> 
> Ok cool , I appreciate it.

I have been participating in hacksquad too . So now i dont know whether it will be counted or not . I have completed my Hacktoberfest , so i want to raise my score in hacksquad , so that's why can you tell me labelling this pr as a spam will be counted or not in hacksquad

**Pull request merged**
